#!/usr/bin/env python3
"""
Validate docs/ markdown metadata compliance.

Checks frontmatter schema for docs/*.md files and regenerates INDEX tables.
Runs as a local sync-docs validator (no external skill dependencies).
"""

import sys
import re
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

REQUIRED_FIELDS = ["title", "scope", "category", "version", "updated"]
VALID_CATEGORIES = {"reference", "guide", "architecture", "api", "plan", "overview"}


def extract_headings(content: str) -> list[tuple[str, str]]:
    results = []
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("## ") and not line.startswith("### "):
            heading = line[3:].strip()
            summary = ""
            j = i + 1
            in_code = False
            while j < len(lines):
                text = lines[j].strip()
                if text.startswith("```"):
                    in_code = not in_code
                    j += 1
                    continue
                if not in_code and text and not text.startswith("#") and not text.startswith("|") and not text.startswith("-"):
                    summary = text.split(".")[0].strip()[:120]
                    break
                j += 1
            results.append((heading, summary))
        i += 1
    return results


def generate_index_table(headings: list[tuple[str, str]]) -> str:
    rows = ["| Section | Summary |", "|---|---|"]
    for heading, summary in headings:
        anchor = heading.lower()
        for ch in "/()":
            anchor = anchor.replace(ch, "")
        anchor = re.sub(r"[\s_]+", "-", anchor)
        anchor = re.sub(r"-+", "-", anchor).strip("-")
        rows.append(f"| [{heading}](#{anchor}) | {summary or '_no summary_'} |")
    return "\n".join(rows) + "\n"


def inject_index(content: str, table: str) -> str:
    header = "<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->\n"
    footer = "<!-- END INDEX -->"
    block = f"{header}{table}{footer}"

    existing = re.search(r"<!-- INDEX:.*?-->.*?<!-- END INDEX -->", content, re.DOTALL)
    if existing:
        return content[: existing.start()] + block + content[existing.end() :]

    fm_match = re.match(r"^(---\n.*?\n---\n)(.*)", content, re.DOTALL)
    if fm_match:
        return fm_match.group(1) + "\n" + block + "\n" + fm_match.group(2)

    return block + "\n" + content


def extract_frontmatter(content: str) -> dict:
    match = re.match(r"^---\n(.*?)\n---\n", content, re.DOTALL)
    if not match:
        return {}

    raw = match.group(1)
    if yaml is not None:
        try:
            return yaml.safe_load(raw) or {}
        except Exception:
            return {}

    data = {}
    for line in raw.splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            data[key.strip()] = value.strip().strip('"')
    return data


def validate_semver(value: str) -> bool:
    return bool(re.match(r"^\d+\.\d+\.\d+$", str(value)))


def validate_date(value: str) -> bool:
    return bool(re.match(r"^\d{4}-\d{2}-\d{2}$", str(value)))


def validate_metadata_file(path: Path) -> bool:
    if not path.exists():
        print(f"ERROR: File not found: {path}")
        return False

    content = path.read_text(encoding="utf-8")
    fm = extract_frontmatter(content)

    errors = []
    warnings = []

    if not fm:
        errors.append("Missing or invalid YAML frontmatter")
    else:
        missing = [k for k in REQUIRED_FIELDS if k not in fm]
        if missing:
            errors.append(f"Missing required fields: {', '.join(missing)}")

        if "category" in fm and fm["category"] not in VALID_CATEGORIES:
            errors.append(
                f"Invalid category '{fm['category']}'. Valid: {', '.join(sorted(VALID_CATEGORIES))}"
            )

        if "version" in fm and not validate_semver(str(fm["version"])):
            errors.append(f"Invalid version format: {fm['version']} (expected x.y.z)")

        if "updated" in fm and not validate_date(str(fm["updated"])):
            errors.append(f"Invalid updated format: {fm['updated']} (expected YYYY-MM-DD)")

        if "source_of_truth_for" in fm and not isinstance(fm["source_of_truth_for"], list):
            warnings.append("source_of_truth_for should be a list")

    print(f"Validating: {path}")
    if errors:
        print("\n❌ ERRORS:")
        for error in errors:
            print(f"  - {error}")
    if warnings:
        print("\n⚠️  WARNINGS:")
        for warning in warnings:
            print(f"  - {warning}")
    if not errors and not warnings:
        print("\n✅ VALID: All checks passed!")

    headings = extract_headings(content)
    if headings:
        table = generate_index_table(headings)
        updated_content = inject_index(content, table)
        if updated_content != content:
            path.write_text(updated_content, encoding="utf-8")
            print("  ✏️  INDEX regenerated.")

    return not errors


def iter_targets(target: Path) -> list[Path]:
    if target.is_dir():
        return sorted(target.glob("*.md"))
    return [target]


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: validate_metadata.py <docs-file-or-directory>")
        sys.exit(1)

    target = Path(sys.argv[1])
    paths = iter_targets(target)
    if not paths:
        print(f"No markdown files found at: {target}")
        sys.exit(1)

    all_ok = True
    for path in paths:
        if not validate_metadata_file(path):
            all_ok = False

    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
