#!/usr/bin/env python3
"""
Generate SSOT memory template with boilerplate metadata.

Creates a new memory file with proper frontmatter structure based on category type.
"""

import sys
from datetime import datetime, timezone
from pathlib import Path


TEMPLATES = {
    "ssot": """---
title: {title}
version: 0.1.0
updated: {timestamp}
scope: {scope}
category: {category}
subcategory: {subcategory}
domain: [{domain}]
applicability: {applicability}
tracks: []
changelog:
  - 0.1.0 ({date}): Initial creation.
---

<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->
| Section | Summary |
|---|---|
<!-- END INDEX -->

## Purpose
{purpose}

## Overview
{overview}

## Key Components

### Component 1
Description...

### Component 2
Description...

## Current State

### What Works
- Item 1
- Item 2

### Known Limitations
- Limitation 1
- Limitation 2

## Related SSOTs
- `related_ssot_1.md` - Description
- `related_ssot_2.md` - Description

## Next Steps
- [ ] Task 1
- [ ] Task 2

## References
- Internal doc references
- External resources
""",

    "pattern": """---
title: {title}
version: 0.1.0
updated: {timestamp}
scope: {scope}
category: pattern
subcategory: {subcategory}
domain: [{domain}]
applicability: {applicability}
tracks: []
changelog:
  - 0.1.0 ({date}): Initial creation.
---

<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->
| Section | Summary |
|---|---|
<!-- END INDEX -->

## Purpose
{purpose}

## Pattern Description
{description}

## When to Apply
- Scenario 1
- Scenario 2

## Implementation

### Approach
Steps to implement this pattern...

### Example
```python
# Code example
```

## Trade-offs

### Benefits
- Benefit 1
- Benefit 2

### Costs
- Cost 1
- Cost 2

## Related Patterns
- `related_pattern_1.md`
- `related_pattern_2.md`
""",

    "reference": """---
title: {title}
scope: {scope}
category: reference
subcategory: {subcategory}
domain: [{domain}]
tracks: []
---

<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->
| Section | Summary |
|---|---|
<!-- END INDEX -->

## Purpose
{purpose}

## Quick Reference

### Category 1
| Item | Description | Example |
|------|-------------|---------|
| Item1 | Desc | `example` |

### Category 2
Details...

## Detailed Documentation

### Section 1
Content...

### Section 2
Content...

## Examples

### Example 1: {example_name}
```
Code or configuration example
```

### Example 2: {example_name}
```
Code or configuration example
```

## Additional Resources
- Link 1
- Link 2
""",

    "plan": """---
title: {title}
version: 0.1.0
updated: {timestamp}
scope: {scope}
category: plan
subcategory: {subcategory}
status: draft
tracks: []
changelog:
  - 0.1.0 ({date}): Initial plan creation.
tracks: []
---

<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->
| Section | Summary |
|---|---|
<!-- END INDEX -->

## Objective
{objective}

## Background
{background}

## Proposed Approach

### Phase 1: {phase_name}
- Task 1
- Task 2

### Phase 2: {phase_name}
- Task 1
- Task 2

## Success Criteria
- [ ] Criterion 1
- [ ] Criterion 2

## Risks & Mitigations
| Risk | Impact | Mitigation |
|------|--------|------------|
| Risk 1 | High | Mitigation strategy |

## Timeline
- Phase 1: Dates
- Phase 2: Dates

## Related Docs
- `related_ssot.md`
- `related_pattern.md`
""",
}


def generate_timestamp():
    """Generate ISO8601 timestamp with timezone."""
    return datetime.now(timezone.utc).isoformat()


def generate_date():
    """Generate YYYY-MM-DD date."""
    return datetime.now().strftime("%Y-%m-%d")


def generate_template(category, **kwargs):
    """Generate memory template from category."""
    if category not in TEMPLATES:
        print(f"ERROR: Invalid category: {category}")
        print(f"Valid categories: {', '.join(TEMPLATES.keys())}")
        sys.exit(1)

    # Merge defaults with user-provided values
    params = {
        "title": "New Memory",
        "timestamp": generate_timestamp(),
        "date": generate_date(),
        "scope": "to-be-defined",
        "category": category,
        "subcategory": "general",
        "domain": "domain1, domain2",
        "applicability": "specific area or 'all'",
        "purpose": "Brief statement of purpose...",
        "overview": "High-level overview...",
        "description": "Detailed description...",
        "objective": "What this plan aims to achieve...",
        "background": "Context and motivation...",
        "phase_name": "Phase Name",
        "example_name": "Example Name",
    }
    params.update(kwargs)

    return TEMPLATES[category].format(**params)


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_template.py <category> <output_filename> [key=value ...]")
        print("")
        print("Categories: ssot, pattern, reference, plan")
        print("")
        print("Examples:")
        print("  generate_template.py ssot analytics_new_ssot.md \\")
        print("      title='New Analytics SSOT' domain='analytics' subcategory='metrics'")
        print("")
        print("  generate_template.py pattern caching_strategy_pattern.md \\")
        print("      title='Caching Strategy Pattern' domain='performance'")
        sys.exit(1)

    category = sys.argv[1]
    output_file = sys.argv[2]

    # Parse optional key=value parameters
    params = {}
    for arg in sys.argv[3:]:
        if '=' in arg:
            key, value = arg.split('=', 1)
            params[key] = value.strip("'\"")

    # Generate template
    content = generate_template(category, **params)

    # Write to file
    output_path = Path(output_file)
    if output_path.exists():
        print(f"ERROR: File already exists: {output_file}")
        print("Use a different filename or remove the existing file first.")
        sys.exit(1)

    output_path.write_text(content, encoding='utf-8')
    print(f"✅ Created {category} memory: {output_file}")
    print(f"📝 Edit the file to fill in placeholders and add content.")


if __name__ == "__main__":
    main()
