#!/usr/bin/env python3
"""
Validate SSOT memory metadata compliance.

Checks if a memory file has all required frontmatter fields and follows
the naming conventions defined in the SSOT guidelines.
"""

import sys
import re
from pathlib import Path
import yaml


def extract_headings(content: str) -> list:
    """Extract (heading, first_sentence) for every ## section (not ###)."""
    results = []
    lines = content.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("## ") and not line.startswith("### "):
            heading = line[3:].strip()
            summary = ""
            j = i + 1
            in_code = False
            while j < len(lines):
                l = lines[j].strip()
                if l.startswith("```"):
                    in_code = not in_code
                    j += 1
                    continue
                if not in_code and l and not l.startswith("#") and not l.startswith("|") and not l.startswith("-"):
                    # Take up to first period, strip trailing period
                    sentence = l.split(".")[0].strip()
                    summary = sentence[:120]
                    break
                j += 1
            results.append((heading, summary))
        i += 1
    return results


def generate_index_table(headings: list) -> str:
    """Generate a full markdown table string from headings list."""
    rows = ["| Section | Summary |", "|---|---|"]
    for heading, summary in headings:
        anchor = heading.lower()
        for ch in "/()":
            anchor = anchor.replace(ch, "")
        anchor = re.sub(r"[\s_]+", "-", anchor)
        anchor = re.sub(r"-+", "-", anchor)
        anchor = anchor.strip("-")
        rows.append(f"| [{heading}](#{anchor}) | {summary or '_no summary_'} |")
    return "\n".join(rows) + "\n"


def inject_index(content: str, table: str) -> str:
    """Replace existing INDEX block or insert one after frontmatter closing ---."""
    header = "<!-- INDEX: auto-generated by validate_metadata.py — do not edit manually -->\n"
    footer = "<!-- END INDEX -->"
    block = f"{header}{table}{footer}"

    # Replace existing block
    existing = re.search(r"<!-- INDEX:.*?-->.*?<!-- END INDEX -->", content, re.DOTALL)
    if existing:
        return content[:existing.start()] + block + content[existing.end():]

    # Insert after second --- (end of frontmatter)
    fm_match = re.match(r"^(---\n.*?\n---\n)(.*)", content, re.DOTALL)
    if fm_match:
        return fm_match.group(1) + "\n" + block + "\n" + fm_match.group(2)

    return block + "\n" + content


REQUIRED_FIELDS = {
    "ssot": ["title", "version", "updated", "scope", "category", "subcategory", "domain"],
    "pattern": ["title", "version", "updated", "scope", "category", "domain"],
    "plan": ["title", "version", "updated", "scope", "category"],
    "reference": ["title", "scope", "category"],
    "archive": ["title", "version", "updated", "scope", "category", "archived_date"],
}

CATEGORY_SUFFIXES = ["ssot", "pattern", "plan", "reference", "archive", "troubleshoot", "commit_log"]


def extract_frontmatter(content):
    """Extract YAML frontmatter from markdown content."""
    match = re.match(r'^---\n(.*?)\n---\n', content, re.DOTALL)
    if not match:
        return None
    try:
        return yaml.safe_load(match.group(1))
    except yaml.YAMLError as e:
        print(f"ERROR: Invalid YAML frontmatter: {e}")
        return None


def validate_naming(filename):
    """Validate filename follows naming conventions."""
    errors = []

    # Check if ends with .md
    if not filename.endswith('.md'):
        errors.append("Filename should end with .md")
        return errors

    stem = filename[:-3]  # Remove .md
    
    # Check if ends with known category suffix
    has_suffix = any(stem.endswith(f"_{suffix}") for suffix in CATEGORY_SUFFIXES)
    if not has_suffix:
        errors.append(f"Filename should end with one of: {', '.join(['_' + s + '.md' for s in CATEGORY_SUFFIXES])}")

    return errors


def validate_version(version):
    """Validate semantic version format (x.y.z)."""
    if not version:
        return False
    pattern = r'^\d+\.\d+\.\d+$'
    return bool(re.match(pattern, str(version)))


def validate_metadata(filepath):
    """Validate memory metadata."""
    path = Path(filepath)

    if not path.exists():
        print(f"ERROR: File not found: {filepath}")
        return False

    print(f"Validating: {path.name}")
    print("=" * 60)

    errors = []
    warnings = []

    # Check naming convention
    naming_errors = validate_naming(path.name)
    errors.extend(naming_errors)

    # Read content
    content = path.read_text(encoding='utf-8')

    # Extract frontmatter
    metadata = extract_frontmatter(content)
    if metadata is None:
        errors.append("Missing or invalid YAML frontmatter (should be between --- markers)")
        print_results(errors, warnings)
        return False

    # Determine category from filename suffix
    category = None
    stem = path.name[:-3]
    for suffix in CATEGORY_SUFFIXES:
        if stem.endswith(f"_{suffix}"):
            category = suffix
            break

    # Check required fields based on category
    # If category is troubleshoot or commit_log, they might not have strict requirements yet
    if category in REQUIRED_FIELDS:
        required = REQUIRED_FIELDS[category]
        missing_fields = [field for field in required if field not in metadata]
        if missing_fields:
            errors.append(f"Missing required fields: {', '.join(missing_fields)}")
    else:
        # Default to ssot requirements if unknown but has suffix
        required = REQUIRED_FIELDS["ssot"]
        missing_fields = [field for field in required if field not in metadata]
        if missing_fields:
            errors.append(f"Missing required fields: {', '.join(missing_fields)}")

    # Validate version format (if present)
    if "version" in metadata:
        if not validate_version(metadata["version"]):
            errors.append(f"Invalid version format: {metadata['version']} (should be x.y.z)")

    # Validate updated timestamp (if present)
    if "updated" in metadata:
        updated = str(metadata["updated"])
        # Check for ISO8601-ish format (basic validation)
        if not re.match(r'^\d{4}-\d{2}-\d{2}', updated):
            warnings.append(f"Updated timestamp should be ISO8601 format: {updated}")

    # Check for domain field (should be array)
    if "domain" in metadata:
        if not isinstance(metadata["domain"], list):
            errors.append("Domain field should be an array/list")

    # Check for changelog in SSOT files
    if category == "ssot" and "changelog" not in metadata:
        warnings.append("SSOT files should include a changelog section in frontmatter")

    print_results(errors, warnings)

    # Regenerate INDEX block unconditionally (navigation aid, independent of schema validity)
    headings = extract_headings(content)
    if headings:
        table = generate_index_table(headings)
        new_content = inject_index(content, table)
        if new_content != content:
            path.write_text(new_content, encoding="utf-8")
            print("  ✏️  INDEX regenerated.")

    return len(errors) == 0


def print_results(errors, warnings):
    """Print validation results."""
    if errors:
        print("\n❌ ERRORS:")
        for error in errors:
            print(f"  - {error}")

    if warnings:
        print("\n⚠️  WARNINGS:")
        for warning in warnings:
            print(f"  - {warning}")

    if not errors and not warnings:
        print("\n✅ VALID: All checks passed!")

    print("=" * 60)


def main():
    if len(sys.argv) < 2:
        print("Usage: validate_metadata.py <memory-file.md>")
        print("Example: validate_metadata.py analytics_volatility_ssot.md")
        sys.exit(1)

    filepath = sys.argv[1]
    success = validate_metadata(filepath)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
