#!/usr/bin/env bash
# Generated by issue-triage skill — triage pass 2026-05-19
# Triage bead: unitAI-9qv4z
# Review before running. All commands already applied.
set -euo pipefail

# Cluster 1: LSP epic missing provenance link
# k5kap description explicitly says it's the structural answer to c4g0m
bd dep add unitAI-k5kap unitAI-c4g0m --type discovered-from

# Cluster 2: Two dolt-server resource issues (post-0wz2p siblings)
bd dep relate unitAI-dp3lg unitAI-3ip52

# Cluster 3: Script-class docs task missing parent link
bd dep add specialists-83y unitAI-z2vpq --type parent-child

# Cluster 4: Throwaway smoke test bead — never closed after test completed
bd kv set "memory-acked:unitAI-pi9ww" "nothing novel: throwaway smoke bead, description said close after smoke"
bd close unitAI-pi9ww --reason="Throwaway smoke bead for bash parallelism test, smoke complete"

echo "Applied 5 mutations from unitAI-9qv4z (triage 2026-05-19)."
